language: r
cache: packages
warnings_are_errors: false

r_packages:
 - devtools
 - roxygen2
 - testthat
  
before_install:
 - R -e "install.packages('devtools')"
 - R -e "install.packages('roxygen2')"
 - R -e "devtools::document()"
 
install:
 - R -e "install.packages('testthat')"
 - R -e "install.packages('ape', '.', repos = 'http://ape-package.ird.fr/')"
 - R -e "devtools::install_github('KlausVigo/phangorn', ref='1167f0be62f13cfad0fca8ae8224318c407195bf')"
 - R -e "devtools::install_github('ms609/TreeSearch')"

r_github_packages:
 - ms609/TreeSearch

#blacklist
branches:
  except:
    - Information
    
git:
  depth: 5

# Needed for phangorn install?  
bioc_required: true
bioc_packages:
  - seqLogo
  - Biostrings
