language: r
cache: packages
warnings_are_errors: false
sudo: required

env: _R_CHECK_CRAN_INCOMING_=FALSE

r_packages:
 - devtools
 - roxygen2
 - testthat
  
install:
 - R -e "install.packages('devtools')"
 - R -e "install.packages('testthat')"
 - R -e "install.packages('ape')"
 - R -e "install.packages('phangorn')"
 - R -e "#devtools::install_github('KlausVigo/phangorn', ref='1167f0be62f13cfad0fca8ae8224318c407195bf')"
 - R -e "devtools::install_github('ms609/TreeSearch')"
 - R -e "install.packages('roxygen2')"
 - R -e "devtools::document()"

r_github_packages:
 - ms609/TreeSearch
 - covr
 - codecov/example-r

#blacklist
branches:
  except:
    - Information
    
git:
  depth: 5

# Needed for phangorn install?  
bioc_required: true
bioc_packages:
  - seqLogo
  - Biostrings
  
after_success:
  - Rscript -e 'library(covr); codecov()'
