#' Thirty Datasets with Inapplicable data
#' 
#' @template 30datasets
#'
#' The name of each item corresponds to the datasets listed below.
#' Datasets are sorted into two subsets, each sorted alphabetically;
#' the first subset comprise simpler datasets with faster processing times.
#' The value is the dataset in the format generated by \code{\link{read.nexus.data}}.
#'
#' @template inapplicableSources
#'
#' @references 
#' @template studyReference
#'
#' @keywords datasets
"inapplicable.datasets"

#' Thirty Datasets with Inapplicable data
#' 
#' @template 30datasets
#'
#' The name of each item corresponds to the datasets listed below.
#' Datasets are sorted into two subsets, each sorted alphabetically;
#' the first subset comprise simpler datasets with faster processing times.
#' The value is the dataset in \code{phyDat} format.
#'
#' @template inapplicableSources
#'
#' @references 
#' @template studyReference
#'
#' @keywords datasets
"inapplicable.phyData"

#' Thirty Datasets with Inapplicable data
#' 
#' @template 30datasets
#'
#' The name of each item corresponds to the datasets listed below.  The value gives its citation.
#'
#' @template inapplicableSources
#'
#' @references
#' @template studyReference
#'
#' @keywords datasets
"inapplicable.citations"
